excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sympl-digital.github.io
title: Awesome
email: 
author: sympl-digital
description: My awesome new site
paginate: 3
google_analytics: 